name: Docker Build And Push

"on":
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: "ubantu-latest"
    steps:
      - name: "Checkout Branch"
        uses: "actions/checkout@v5"

      - name: "Login to Docker"
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request'}}
          tags: career-top:latest
          context: .
